### ISSUE TITLE
US07 Eu, como desenvolvedor, devo criar um arquivo JSON com perguntas e respostas do jogo

### ISSUE THREAD

**Issue by jullysilva** [frattezi/passa-palavra#21]
- [x] O desenvolvedor deve criar um arquivo que armazene perguntas e respostas.

- [x] O desenvolvedor deve criar uma pergunta e resposta para cada letra do alfabeto.

**Comment by frattezi** [comment]
Isso aqui não está em doing pelo Wesley?
